"""Tests für thunderbird_konten.py gegen ein Test-Profil im tmp-Ordner: python3 -m unittest test_thunderbird_konten.py"""
import ctypes.util
import importlib.util
import io
import json
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

HERE = Path(__file__).parent
spec = importlib.util.spec_from_file_location("thunderbird_konten", HERE / "thunderbird_konten.py")
tk = importlib.util.module_from_spec(spec)
sys.modules["thunderbird_konten"] = tk
spec.loader.exec_module(tk)

MUSTER_PREFS = '''// Mozilla User Preferences

// DO NOT EDIT THIS FILE.

user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.lastKey", 2);
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server2");
user_pref("mail.identity.id1.draft_folder", "imap://info%40strainovic-it.ch@mail.infomaniak.com/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "1");
user_pref("mail.identity.id1.fcc_folder", "imap://info%40strainovic-it.ch@mail.infomaniak.com/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "1");
user_pref("mail.identity.id1.fullName", "Goran Strainovic");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.useremail", "info@strainovic-it.ch");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.server.server1.authMethod", 3);
user_pref("mail.server.server1.hostname", "mail.infomaniak.com");
user_pref("mail.server.server1.name", "info@strainovic-it.ch");
user_pref("mail.server.server1.port", 993);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.userName", "info@strainovic-it.ch");
user_pref("mail.server.server2.hostname", "Local Folders");
user_pref("mail.server.server2.name", "Lokale Ordner");
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.userName", "nobody");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.hostname", "mail.infomaniak.com");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.username", "info@strainovic-it.ch");
user_pref("mail.smtpservers", "smtp1");
'''

ACCOUNTS = '''
[strainovic]
address = "info@strainovic-it.ch"
name = "Goran Strainovic"
imap = "mail.infomaniak.com"
smtp = "mail.infomaniak.com"
password_file = "{tmp}/strainovic.pass"
sent_folder = "Sent"

[strainovic-dev]
address = "info@strainovic-it.dev"
login = "info@strainovic-it.ch"
name = "Goran Strainovic"
imap = "mail.infomaniak.com"
smtp = "mail.infomaniak.com"
password_file = "{tmp}/strainovic.pass"
sent_folder = "Sent"

[ki-flows]
address = "info@ki-flows.ch"
name = "Goran Strainovic"
imap = "mail.infomaniak.com"
smtp = "mail.infomaniak.com"
password_file = "{tmp}/ki-flows.pass"
sent_folder = "Sent"
'''

GEHEIM = "Geheim-Kennwort-123"


class Testprofil:
    """Thunderbird-Wurzel mit profiles.ini/installs.ini, ein Profil, accounts.toml und Passwortdatei."""

    def __init__(self, tmp, logins=None):
        self.tmp = Path(tmp)
        self.root = self.tmp / "tb"
        self.profil = self.root / "abc123.default-esr"
        self.profil.mkdir(parents=True)
        (self.root / "anderes.default").mkdir()
        (self.root / "profiles.ini").write_text(
            "[Profile1]\nName=default\nIsRelative=1\nPath=anderes.default\nDefault=1\n\n"
            "[Profile0]\nName=default-esr\nIsRelative=1\nPath=abc123.default-esr\n\n"
            "[General]\nStartWithLastProfile=1\nVersion=2\n\n"
            "[InstallBD520B11F73A6B64]\nDefault=abc123.default-esr\nLocked=1\n")
        (self.root / "installs.ini").write_text("[BD520B11F73A6B64]\nDefault=abc123.default-esr\nLocked=1\n")
        self.prefs.write_text(MUSTER_PREFS)
        if logins is not None:
            self.logins.write_text(json.dumps(logins))
        self.accounts = self.tmp / "accounts.toml"
        self.accounts.write_text(ACCOUNTS.format(tmp=self.tmp))
        (self.tmp / "strainovic.pass").write_text("altes-kennwort\n")
        (self.tmp / "ki-flows.pass").write_text(GEHEIM + "\n")

    @property
    def prefs(self):
        return self.profil / "prefs.js"

    @property
    def logins(self):
        return self.profil / "logins.json"

    def lauf(self, *extra, laeuft=False, nss=False):
        out = io.StringIO()
        argv = ["--tb-root", str(self.root), "--accounts", str(self.accounts), *extra]
        if not nss:
            argv.append("--ohne-passwoerter")
        with redirect_stdout(out):
            rc = tk.main(argv, thunderbird_laeuft=lambda: laeuft)
        return rc, out.getvalue()

    def pref(self, key):
        return tk.lese_prefs(self.prefs.read_text()).get(key)


class KontenAbgleich(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.p = Testprofil(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def test_fehlendes_postfach_erscheint_als_imap_konto_mit_smtp(self):
        rc, out = self.p.lauf()
        self.assertEqual(rc, 0)
        prefs = tk.lese_prefs(self.p.prefs.read_text())
        server = [k.split(".")[2] for k, v in prefs.items()
                  if k.endswith(".userName") and v == "info@ki-flows.ch"]
        self.assertEqual(len(server), 1)
        s = f"mail.server.{server[0]}"
        self.assertEqual(prefs[f"{s}.type"], "imap")
        self.assertEqual(prefs[f"{s}.hostname"], "mail.infomaniak.com")
        self.assertEqual(prefs[f"{s}.port"], 993)
        self.assertEqual(prefs[f"{s}.socketType"], 3)
        konto = [k.split(".")[2] for k, v in prefs.items() if k.endswith(".server") and v == server[0]][0]
        self.assertIn(konto, prefs["mail.accountmanager.accounts"].split(","))
        ident = prefs[f"mail.account.{konto}.identities"]
        self.assertEqual(prefs[f"mail.identity.{ident}.useremail"], "info@ki-flows.ch")
        self.assertEqual(prefs[f"mail.identity.{ident}.fullName"], "Goran Strainovic")
        self.assertEqual(prefs[f"mail.identity.{ident}.fcc_folder"],
                         "imap://info%40ki-flows.ch@mail.infomaniak.com/Sent")
        smtp = prefs[f"mail.identity.{ident}.smtpServer"]
        self.assertIn(smtp, prefs["mail.smtpservers"].split(","))
        self.assertEqual(prefs[f"mail.smtpserver.{smtp}.hostname"], "mail.infomaniak.com")
        self.assertEqual(prefs[f"mail.smtpserver.{smtp}.port"], 465)
        self.assertEqual(prefs[f"mail.smtpserver.{smtp}.try_ssl"], 3)
        self.assertEqual(prefs[f"mail.smtpserver.{smtp}.username"], "info@ki-flows.ch")
        self.assertIn("info@ki-flows.ch", out)
        # Lokale Ordner bleiben am Ende der Liste
        self.assertEqual(prefs["mail.accountmanager.accounts"].split(",")[-1], "account2")

    def test_alias_wird_identitaet_im_vorhandenen_konto(self):
        self.p.lauf()
        prefs = tk.lese_prefs(self.p.prefs.read_text())
        idents = prefs["mail.account.account1.identities"].split(",")
        self.assertEqual(idents[0], "id1")
        self.assertEqual(len(idents), 2)
        neu = idents[1]
        self.assertEqual(prefs[f"mail.identity.{neu}.useremail"], "info@strainovic-it.dev")
        self.assertEqual(prefs[f"mail.identity.{neu}.smtpServer"], "smtp1")
        self.assertEqual(prefs[f"mail.identity.{neu}.fcc_folder"],
                         "imap://info%40strainovic-it.ch@mail.infomaniak.com/Sent")
        # kein zweites Postfach für den Login info@strainovic-it.ch
        logins = [v for k, v in prefs.items() if k.endswith(".userName") and v == "info@strainovic-it.ch"]
        self.assertEqual(len(logins), 1)

    def test_bestehende_einstellungen_bleiben_wortgleich(self):
        vorher = MUSTER_PREFS.splitlines()
        self.p.lauf()
        nachher = self.p.prefs.read_text().splitlines()
        listen = ("mail.accountmanager.accounts", "mail.account.account1.identities",
                  "mail.account.lastKey", "mail.smtpservers")
        for zeile in vorher:
            if any(f'"{k}"' in zeile for k in listen):
                continue
            self.assertIn(zeile, nachher)

    def test_zweiter_lauf_aendert_nichts(self):
        self.p.lauf()
        stand = self.p.prefs.read_bytes()
        sicherungen = sorted(self.p.profil.glob("prefs.js.*"))
        rc, out = self.p.lauf()
        self.assertEqual(rc, 0)
        self.assertEqual(self.p.prefs.read_bytes(), stand)
        self.assertEqual(sorted(self.p.profil.glob("prefs.js.*")), sicherungen)
        rc, out = self.p.lauf("--dry-run")
        self.assertIn("nichts zu tun", out)

    def test_trockenlauf_zeigt_fehlendes_und_aendert_nichts(self):
        rc, out = self.p.lauf("--dry-run")
        self.assertEqual(rc, 0)
        self.assertEqual(self.p.prefs.read_text(), MUSTER_PREFS)
        self.assertIn("info@ki-flows.ch", out)
        self.assertIn("info@strainovic-it.dev", out)
        # vorhandenes Postfach wird nicht als fehlend gemeldet
        self.assertNotIn("Postfach info@strainovic-it.ch", out)
        self.assertEqual(len([z for z in out.splitlines() if z.startswith("  ")]), 2)
        self.assertEqual(list(self.p.profil.glob("prefs.js.*")), [])

    def test_bricht_ab_wenn_thunderbird_laeuft(self):
        rc, out = self.p.lauf(laeuft=True)
        self.assertNotEqual(rc, 0)
        self.assertIn("Thunderbird läuft", out)
        self.assertEqual(self.p.prefs.read_text(), MUSTER_PREFS)

    def test_sichert_prefs_vor_der_aenderung(self):
        self.p.lauf()
        sicherung = list(self.p.profil.glob("prefs.js.vor-thunderbird-konten-*"))
        self.assertEqual(len(sicherung), 1)
        self.assertEqual(sicherung[0].read_text(), MUSTER_PREFS)

    def test_profil_aus_installs_ini_statt_profiles_default(self):
        self.p.lauf()
        self.assertFalse((self.p.root / "anderes.default" / "prefs.js").exists())
        self.assertIn("info@ki-flows.ch", self.p.prefs.read_text())

    def test_unbekanntes_ausgangsserver_schema_bricht_ab(self):
        self.p.prefs.write_text(MUSTER_PREFS + 'user_pref("mail.outgoingservers", "smtp1");\n')
        rc, out = self.p.lauf()
        self.assertNotEqual(rc, 0)
        self.assertIn("mail.outgoingserver", out)


LIBNSS = ctypes.util.find_library("nss3")


@unittest.skipUnless(LIBNSS, "libnss3 fehlt")
class Passwoerter(unittest.TestCase):
    """Echtes NSS im tmp-Profil: NSS legt key4.db im leeren Ordner an."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.vorhanden = {"nextId": 2, "potentiallyVulnerablePasswords": [], "version": 3, "logins": [
            {"id": 1, "hostname": "imap://mail.infomaniak.com", "httpRealm": "imap://mail.infomaniak.com",
             "formSubmitURL": None, "usernameField": "", "passwordField": "", "encryptedUsername": "ALT",
             "encryptedPassword": "ALT", "guid": "{alt}", "encType": 1, "timeCreated": 1, "timeLastUsed": 1,
             "timePasswordChanged": 1, "timesUsed": 1}]}
        self.p = Testprofil(self._tmp.name, logins=self.vorhanden)

    def tearDown(self):
        self._tmp.cleanup()

    def neue_logins(self):
        return [l for l in json.loads(self.p.logins.read_text())["logins"] if l["guid"] != "{alt}"]

    def test_passwort_verschluesselt_in_logins_json_und_nie_in_der_ausgabe(self):
        rc, out = self.p.lauf(nss=True)
        self.assertEqual(rc, 0, out)
        self.assertNotIn(GEHEIM, out)
        self.assertNotIn(GEHEIM, self.p.logins.read_text())
        daten = json.loads(self.p.logins.read_text())
        self.assertEqual(daten["logins"][0], self.vorhanden["logins"][0])
        neu = self.neue_logins()
        self.assertEqual(sorted(l["hostname"] for l in neu),
                         ["imap://mail.infomaniak.com", "smtp://mail.infomaniak.com"])
        nss = tk.Nss(self.p.profil)
        for l in neu:
            self.assertEqual(l["httpRealm"], l["hostname"])
            self.assertEqual(l["encType"], 1)
            self.assertEqual(nss.entschluesseln(l["encryptedUsername"]), "info@ki-flows.ch")
            self.assertEqual(nss.entschluesseln(l["encryptedPassword"]), GEHEIM)
        self.assertEqual(sorted(l["id"] for l in neu), [2, 3])
        self.assertEqual(daten["nextId"], 4)
        self.assertTrue(list(self.p.profil.glob("logins.json.vor-thunderbird-konten-*")))
        self.assertIn("Passwörter gespeichert", out)

    def test_zweiter_lauf_legt_keine_doppelten_logins_an(self):
        self.p.lauf(nss=True)
        stand = self.p.logins.read_bytes()
        rc, out = self.p.lauf(nss=True)
        self.assertEqual(rc, 0)
        self.assertEqual(self.p.logins.read_bytes(), stand)


if __name__ == "__main__":
    unittest.main()
